name:                colabzy
version:             0.1.0.0
github:              "githubuser/colabzy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/colabzy#readme>

dependencies:
- base >= 4.7 && < 5
- scotty >= 0.11.4
- text >= 1.2.3.1
- wai >= 3.2.2
- wai-extra >= 3.0.26
- network >= 2.8.0.1
- warp >= 3.2.2
- websockets >= 0.12.5.3
- wai-websockets >= 3.0.1.2
- data-default >= 0.7.1.1
- wai-middleware-static >= 0.8.2
- uuid >= 1.3.13

library:
  main:                  Main.hs

executables:
  colabzy-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - colabzy

tests:
  colabzy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - colabzy
